version: '3.1'

networks:
  app:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    networks:
      - app
  db_postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - '54322:5432'
    networks:
      - app
